"""empty message

Revision ID: da79cfaca79a
Revises: 0b15502f56e3
Create Date: 2024-06-15 19:09:35.163306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da79cfaca79a'
down_revision = '0b15502f56e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.drop_constraint('coins_id_coin_wallet_fkey', type_='foreignkey')
        batch_op.drop_column('id_coin_wallet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_coin_wallet', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('coins_id_coin_wallet_fkey', 'wallets', ['id_coin_wallet'], ['id_wallet'])

    # ### end Alembic commands ###
