@startuml
class Account {
    - id_account: int
    - total_balance: float
    - is_admin: bool
    - dni: int
    - username: str
    - name: str
    - surname: str
    - birthdate: dates
    - phone: str
    - address: str
    - email: str
    - password: str
    --
    + get_data_account ()   
    + set_data_account ()
    + get_balance ()
    + make_balance ()
    + swap ()
}

note right of Account::get_data_account
This method returns the data of a user
end note

class Admin {
    <<extend>>User
    +cvu: int
    --
    +upload_money ()
    +get_other_account_info (DNI)
}


class Register{
    -id_register: int
    -operation_date: date
    -motion: str
    -amount_1: float
    -amount_2: float
    -id_wallet_1: int
    -id_wallet_2: int
    --
    +equate_coins ()
    +get_motion () 
}

Class Coin {
    -id_coin: int
    -coin_name: str
    -abbreviation: str
    -price: float
    -time_variation: float
    --
    +get_price ()
    +set_price ()
    +get_variation ()
    +set_variation ()
}
note right  of Coin::get_price
Returns the price in USD.
end note
note  right of Coin::get_variation
Returns its variation from x time.
end note

Class Wallet{
    -id_wallet: int
    -balance: float
    -id_owner_account: int
    -id_wallet_coin: int
}

Account <|--  Admin



Wallet "1" *-- "1" Register

Account "1"*-- "1" Wallet

Wallet *-- Coin